/**
 * Writes landing/pages.json: every rule that gets a page of its own, and the
 * figures that page prints.
 *
 *     node --import ./tests/js/resolve-shared.mjs tools/id-photo/landing/emit.mjs
 *
 * WHY THERE IS A FILE AT ALL
 *
 * Somebody searching "Canada passport photo size" wants Canada's numbers, the
 * name of whoever published them and the day they were last read - and the
 * tool's own page cannot answer that, because it is one address holding
 * sixty-seven rules behind a menu. So each rule with figures of its own gets an
 * address of its own: /id-photo/ca-passport/. The build writes those pages, the
 * build is Python, and the rulebook is src/specs.js. This file is how the one
 * reads the other without the numbers being typed out a second time.
 *
 * WHY IT HOLDS KEYS AND NOT SENTENCES
 *
 * The rows are made by specFacts() in src/files.js - the same function the
 * panel under the chooser calls - handed a `t` that returns what it was asked
 * for instead of answering: { key: 'print.size', values: { width: '51', ... } }.
 * The build resolves those against the #phrases block of each language's
 * body.html, which is where the tool itself gets its words. So a landing page
 * says what the tool says, in every language the tool says it in, and there is
 * no second table of labels to translate or to drift.
 *
 * WHICH RULES
 *
 * A portrait, with a citation in src/sources.js, whose authority publishes
 * figures. That leaves out the signature, the sizes that are common practice
 * rather than anybody's rule, the form you fill in yourself, and the countries
 * listed with `published: 'words'` - a page saying "Sweden publishes no
 * measurements" is a true sentence and a thin page, and the tool already says
 * it to anybody who picks Sweden.
 *
 * WHY THE FILE IS COMMITTED
 *
 * The build runs without Node, on purpose. tests/js/id-photo-landing.test.js
 * fails when this file would write something other than what is committed, so
 * a rule changed without running it is a red build and not a page quoting last
 * month's numbers.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { SPECS, backgroundOf } from '../src/specs.js';
import { ENDONYMS, SOURCES } from '../src/sources.js';
import { docSize, sourceLine, specFacts } from '../src/files.js';

const OUTPUT = new URL('./pages.json', import.meta.url);

/** The question, handed back: what phrase() was asked for, not its answer. */
const asked = (key, values) => (values ? { key, values } : { key });

/** Does this rule get a page? See "which rules" above. */
export const hasPage = (spec) => (
  spec.kind === 'portrait' && !spec.published && Object.hasOwn(SOURCES, spec.id));

export function pages() {
  return SPECS.filter(hasPage).map((spec) => ({
    id: spec.id,
    country: spec.country,
    endonym: ENDONYMS[spec.country] ?? null,
    document: spec.document,
    native: spec.native ?? null,
    size: docSize(spec, asked),
    // As a sentence carries it - "white or off-white" - for the description.
    background: backgroundOf(spec, asked).inline,
    facts: specFacts(spec, asked),
    notes: spec.notes,
    source: sourceLine(spec, asked),
    authority: spec.source.authority,
    checked: spec.source.checked,
  }));
}

/** The file's bytes. LF, and a closing newline, like everything else here. */
export const rendered = () => `${JSON.stringify({
  about: 'Generated by tools/id-photo/landing/emit.mjs from src/specs.js. Do not edit; run it.',
  pages: pages(),
}, null, 2)}\n`;

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OUTPUT, rendered());
  console.log(`pages.json: ${pages().length} rules`);
}
