<#
.SYNOPSIS
  Applies cloudflare/redirects.json as the zone's Single Redirect rules, then
  checks that every old address really answers 301 to the new one.

.DESCRIPTION
  A renamed tool leaves a stub at its old address - a meta refresh, a canonical
  and `noindex` - because GitHub Pages cannot answer 301. Cloudflare can, and
  it answers before the request reaches the stub. redirects.json is that list
  of answers, generated by redirects.py from [redirects] in config/site.toml;
  the top of that script says why a 301 is worth having when the stub already
  moves the reader, and why German is left to its stubs.

  IMPORTANT: like apply-headers.ps1, this REPLACES every rule in the phase -
  here http_request_dynamic_redirect, which the dashboard calls Redirect Rules.
  A redirect clicked together in the dashboard disappears the next time this
  runs. Run -Export first, and put anything it shows that is worth keeping
  where it can be generated or reviewed.

  The file is sent byte for byte. It is also checked against the configuration
  before anything is sent: a file that redirects.py would no longer write is a
  file somebody forgot to regenerate, and applying it would publish last
  month's addresses.

.PARAMETER Token
  Cloudflare API token. Defaults to $env:CLOUDFLARE_API_TOKEN.
  Needs Zone / Single Redirect / Edit, plus Zone / Zone / Read if you want the
  zone ID looked up from the domain name rather than passing it in. Those are
  rows in the token form - three dropdowns, of which "Zone" is the first - and
  not a place in the dashboard. Write-ups elsewhere call the permission
  "Dynamic Redirect", after the phase; the form lists it as Single Redirect.
  The headers' token does not carry it; one token may hold both. -Export is
  the way to find out whether a token does: it only reads.

.PARAMETER ZoneId
  Zone ID. Defaults to $env:CLOUDFLARE_ZONE_ID, and is otherwise looked up from
  -Domain.

.PARAMETER Domain
  The zone name, used for the lookup and for the verification requests.

.PARAMETER Export
  Print the redirect rules currently live in the zone and stop.

.PARAMETER VerifyOnly
  Skip the write and just ask the live site for every old address. Needs no
  token. Before the first apply, every line reads "still the stub".

.PARAMETER DryRun
  Print the payload and the target URL, then stop without sending anything.

.EXAMPLE
  $env:CLOUDFLARE_API_TOKEN = "..."
  .\cloudflare\apply-redirects.ps1 -Export

.EXAMPLE
  .\cloudflare\apply-redirects.ps1

.EXAMPLE
  .\cloudflare\apply-redirects.ps1 -VerifyOnly
#>

[CmdletBinding()]
param(
  [string] $Token  = $env:CLOUDFLARE_API_TOKEN,
  [string] $ZoneId = $env:CLOUDFLARE_ZONE_ID,
  [string] $Domain = "abox.tools",
  [switch] $Export,
  [switch] $VerifyOnly,
  [switch] $DryRun
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "cf-api.ps1")

$phase       = "http_request_dynamic_redirect"
$payloadPath = Join-Path $PSScriptRoot "redirects.json"

# ---- what the payload asks for -------------------------------------------

if (-not (Test-Path $payloadPath)) { throw "Payload not found: $payloadPath. Run: python cloudflare/redirects.py" }

# Bytes rather than Get-Content: Windows PowerShell reads a file with no BOM as
# ANSI, and a description naming a localized address would reach Cloudflare as
# something other than what is committed.
$bytes   = [IO.File]::ReadAllBytes($payloadPath)
$rawJson = [Text.Encoding]::UTF8.GetString($bytes)
try {
  $payload = $rawJson | ConvertFrom-Json
} catch {
  throw "redirects.json is not valid JSON: $($_.Exception.Message)"
}

# Every old address and where it should lead, read back out of the rules
# themselves so that what is verified is what was sent and not a second list.
$moves = @()
foreach ($rule in $payload.rules) {
  $target = $rule.action_parameters.from_value.target_url.value
  foreach ($match in [regex]::Matches($rule.expression, '"(/[^"]*)"')) {
    $moves += [pscustomobject]@{ From = $match.Groups[1].Value; To = $target }
  }
}

Write-Step "Payload: $($payload.rules.Count) rule(s), $($moves.Count) old address(es)"
foreach ($rule in $payload.rules) { Write-Host "  $($rule.description)" }

# ---- export: what is live right now --------------------------------------

if ($Export) {
  Assert-Token
  $zone = Resolve-ZoneId
  Write-Step "Rules currently live in the $phase phase"
  try {
    $live = Invoke-Cf "GET" "https://api.cloudflare.com/client/v4/zones/$zone/rulesets/phases/$phase/entrypoint" $null
  } catch {
    # A zone that has never had a redirect rule has no entrypoint ruleset yet,
    # and the API says so with a 404 rather than an empty list.
    if ("$_" -match "could not find entrypoint|10003|404") { Write-Host "  (none - the phase has never been used)"; return }
    throw
  }
  if (-not $live.result.rules -or $live.result.rules.Count -eq 0) {
    Write-Host "  (none - the phase is empty)"
  } else {
    $live.result.rules | ConvertTo-Json -Depth 10
    Write-Host "`nCompare this with redirects.json before applying." -ForegroundColor Yellow
    Write-Host "Anything live but not in the file will be removed by an apply."
  }
  return
}

# ---- apply ---------------------------------------------------------------

if (-not $VerifyOnly) {
  # Refuse a stale file before asking for a token, so the mistake is named
  # while it is still cheap. Skipped only when there is no Python to ask.
  $python = Get-Command python -ErrorAction SilentlyContinue
  if ($python) {
    & $python.Source (Join-Path $PSScriptRoot "redirects.py") --check
    if ($LASTEXITCODE -ne 0) { throw "redirects.json no longer matches config/site.toml. Regenerate it, commit it, then apply." }
  } else {
    Write-Host "  python not found - cannot confirm redirects.json is current." -ForegroundColor Yellow
  }

  Assert-Token
  $zone = Resolve-ZoneId
  $url  = "https://api.cloudflare.com/client/v4/zones/$zone/rulesets/phases/$phase/entrypoint"

  if ($DryRun) {
    Write-Step "Dry run - would PUT to:"
    Write-Host "  $url"
    Write-Host $rawJson
    return
  }

  Write-Step "PUT $url"
  Write-Host "  This replaces every rule in the $phase phase." -ForegroundColor Yellow

  $result = Invoke-Cf "PUT" $url $bytes

  if (-not $result.success) {
    throw "Cloudflare rejected the ruleset: $($result.errors | ConvertTo-Json -Depth 5)"
  }
  Write-Host "  Applied. Ruleset $($result.result.id), version $($result.result.version)." -ForegroundColor Green

  # The API answers before the edge has the rules. Asked the same second, all
  # twenty addresses were still the stub, and twenty seconds later all twenty
  # answered 301 - a verify that cries wolf on every successful apply teaches
  # whoever runs it to ignore the verify.
  Write-Host "  Giving the edge twenty seconds to pick them up before asking."
  Start-Sleep -Seconds 20
}

# ---- verify against the live site ----------------------------------------

Write-Step "Asking https://$Domain for every old address"

$wrong = 0
foreach ($move in $moves) {
  $answer = Get-EdgeAnswer "https://$Domain$($move.From)" $null
  if ($answer.Status -eq 301 -and $answer.Location -eq $move.To) {
    Write-Host ("  ok       {0,-32} 301 {1}" -f $move.From, $answer.Location) -ForegroundColor Green
  } elseif ($answer.Status -eq 200) {
    Write-Host ("  STUB     {0,-32} 200 - still the stub, the rule is not answering" -f $move.From) -ForegroundColor Yellow
    $wrong++
  } elseif ($answer.Status -eq 301) {
    # GitHub Pages answers 301 by itself for an address without its closing
    # slash, so a 301 to the wrong place is the origin talking, not the rule.
    Write-Host ("  ELSEWHERE {0,-31} 301 {1}" -f $move.From, $answer.Location) -ForegroundColor Yellow
    $wrong++
  } else {
    Write-Host ("  WRONG    {0,-32} {1} {2}" -f $move.From, $answer.Status, $answer.Note) -ForegroundColor Red
    $wrong++
  }
}

if ($wrong -gt 0) {
  Write-Host "`n$wrong old address(es) not redirected at the edge." -ForegroundColor Yellow
  Write-Host "If nothing has been applied yet, that is what this looks like. Otherwise the"
  Write-Host "usual cause is a DNS record that is not proxied - rules only run on traffic"
  Write-Host "that goes through Cloudflare (orange cloud, not grey)."
} else {
  Write-Host "`nEvery old address answers 301 to where its tool lives now." -ForegroundColor Green
}
